name: Test On Push
run-name: Test On Push
on:
  push:
    branches: 
      - main

jobs:
  test-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello from Test on Push"
