name: Test On Pull Request
run-name: Run Name Test On Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  test-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
